<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_55QxzY2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.55QxzY2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.55QxzY2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pathRepository' => ['privates', 'App\\Repository\\PathRepository', 'getPathRepositoryService', true],
        ], [
            'pathRepository' => 'App\\Repository\\PathRepository',
        ]);
    }
}
