<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_COnnS9XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.COnnS9X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.COnnS9X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ligne' => ['privates', '.errored..service_locator.COnnS9X.App\\Entity\\Ligne', NULL, 'Cannot autowire service ".service_locator.COnnS9X": it references class "App\\Entity\\Ligne" but no such service exists.'],
        ], [
            'ligne' => 'App\\Entity\\Ligne',
        ]);
    }
}
