<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3WQU2RxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3WQU2Rx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3WQU2Rx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'path' => ['privates', '.errored..service_locator.3WQU2Rx.App\\Entity\\Path', NULL, 'Cannot autowire service ".service_locator.3WQU2Rx": it references class "App\\Entity\\Path" but no such service exists.'],
        ], [
            'path' => 'App\\Entity\\Path',
        ]);
    }
}
