<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AoBNGuCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aoBNGuC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aoBNGuC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'timing' => ['privates', '.errored..service_locator.aoBNGuC.App\\Entity\\Timing', NULL, 'Cannot autowire service ".service_locator.aoBNGuC": it references class "App\\Entity\\Timing" but no such service exists.'],
        ], [
            'timing' => 'App\\Entity\\Timing',
        ]);
    }
}
