<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPathService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3WQU2Rx.App\Entity\Path' shared service.
     *
     * @return \App\Entity\Path
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.3WQU2Rx": it references class "App\\Entity\\Path" but no such service exists.');
    }
}
