<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FE.T52b.App\Entity\Site' shared service.
     *
     * @return \App\Entity\Site
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FE.T52b": it references class "App\\Entity\\Site" but no such service exists.');
    }
}
