<?php

namespace Container9RIxCPJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aoBNGuC.App\Entity\Timing' shared service.
     *
     * @return \App\Entity\Timing
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aoBNGuC": it references class "App\\Entity\\Timing" but no such service exists.');
    }
}
