<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9RIxCPJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9RIxCPJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9RIxCPJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9RIxCPJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9RIxCPJ\App_KernelDevDebugContainer([
    'container.build_hash' => '9RIxCPJ',
    'container.build_id' => '673c82b2',
    'container.build_time' => 1605816152,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9RIxCPJ');
